services:
  - type: web
    name: jijenge-loans-backend
    env: node
    region: singapore
    plan: starter
    rootDir: backend
    buildCommand: npm install --include=dev && npm run prisma:dbpush && npm run prisma:generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PALPLUSS_API_KEY
        sync: false
      - key: PALPLUSS_CHANNEL_ID
        value: "1"
      - key: PALPLUSS_WEBHOOK_SECRET
        generateValue: true
      - key: SMSGATEWAY_USERNAME
        sync: false
      - key: SMSGATEWAY_PASSWORD
        sync: false
      - key: SUPER_ADMIN_USER
        sync: false
      - key: SUPER_ADMIN_PASS
        sync: false
